[package]
name = "vers"
version = "0.1.0"
edition = "2021"
description = "Install and manage dev tools with multiple environments"
repository = "https://github.com/reynn/vers"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities"]

[package.metadata.bundle]
name = "vers"
identifier = "dev.reynn.vers"

[dependencies]
async-trait = "0.1"
cargo = "0.62"
cargo-util = "0.1"
clap = "3.1"
clap-verbosity-flag = "1.0"
clap_complete = "3.1"
directories-next = "2.0"
env_logger = "0.9"
eyre = "0.6"
is_executable = "1.0"
log = "0.4"
octocrab = "0.16"
once_cell = "1.12"
regex = "1.5"
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.13"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
skim = "0.9"
test-case = "2.1"
tokio = { version = "1.19", features = ["full"] }
toml = "0.5"
url = "2.2"
walkdir = "2.3"
