[package]
name = "vers"
version = "0.1.0"
edition = "2021"
description = "Install and manage dev tools with multiple environments"
repository = "https://github.com/reynn/vers"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities"]

[package.metadata.bundle]
name = "vers"
identifier = "dev.reynn.vers"

[dependencies]
async-trait = "0.1"
bpaf = { version = "0.4", features = ["derive"] }
directories-next = "2.0"
env_logger = "0.9"
eyre = "0.6"
is_executable = "1.0"
log = "0.4"
octocrab = "0.16"
once_cell = "1.10"
regex = "1.5"
reqwest = "0.11"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
skim = "0.9"
test-case = "2.0"
tokio = { version = "1.18", features = ["full"] }
toml = "0.5"
walkdir = "2.3"
