[package]
name = "vers-github"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
async-trait = "0.1"
eyre = "0.6"
log = "0.4"
vers = { path = "../.." }
wasm-bindgen = "0.2"
